version: "3.5"
services:
  db:
    container_name: db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "DummyPassw0rdForTesting!!" # As stated in the official doc: The password must be at least 8 characters long and contain characters from three of the following four sets: Uppercase letters, Lowercase letters, Base 10 digits, and Symbols.
      ACCEPT_EULA: "Y"
      MSSQL_USER: sa
